title: Arsh Dhillon
logo: "/images/photo.jpg?raw=true"
description: >
  UoW'22 Elecrical and Computer Engineering, Minor in Mathematics 
  <br><br>
  Interested in IT, Software, Power Systems, Web and Game Dev, Electronics, Computers, Music and Pizza  
  <br><br>
  <a href="https://www.linkedin.com/in/arsh-dhillon/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
